//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_Navettes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class abonnement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public abonnement()
        {
            this.reservation = new HashSet<reservation>();
        }
    
        public int id_abn { get; set; }
        [Required]
        public string ville_depart { get; set; }
        [Required]
        public string ville_arrive { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime date_depart { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public System.DateTime date_arrive { get; set; }
        public string abn_image { get; set; }
        [Required]
        public string heur_depart { get; set; }
        [Required]
        public string descr { get; set; }

        public int type_abn { get; set; }       
        public Nullable<int> id_vh { get; set; }
        public Nullable<int> id_soc { get; set; }
        [Required]
        public Nullable<double> prix { get; set; }
        [Required]
        public string heur_arrive { get; set; }
    
        public virtual societe societe { get; set; }
        public virtual vehicule vehicule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reservation> reservation { get; set; }
    }
}
